global using System.Net.Http.Json;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using MudBlazor.Services;
global using FLLJudge.Client.Pages;
global using FLLJudge.Shared;